// Code generated by internal/cmd/generator. DO NOT EDIT!
package server

import "net/http"

type Handler struct {
	Path       string
	HTTPMethod string
	Handler    http.Handler
}

var handlers = []*Handler{
	{
		Path:       "/projects/{projectId}/datasets/{datasetId}",
		HTTPMethod: "DELETE",
		Handler:    &datasetsDeleteHandler{},
	},
	{
		Path:       "/projects/{projectId}/datasets/{datasetId}",
		HTTPMethod: "GET",
		Handler:    &datasetsGetHandler{},
	},
	{
		Path:       "/projects/{projectId}/datasets",
		HTTPMethod: "POST",
		Handler:    &datasetsInsertHandler{},
	},
	{
		Path:       "/projects/{projectId}/datasets",
		HTTPMethod: "GET",
		Handler:    &datasetsListHandler{},
	},
	{
		Path:       "/projects/{projectId}/datasets/{datasetId}",
		HTTPMethod: "PATCH",
		Handler:    &datasetsPatchHandler{},
	},
	{
		Path:       "/projects/{projectId}/datasets/{datasetId}",
		HTTPMethod: "PUT",
		Handler:    &datasetsUpdateHandler{},
	},
	{
		Path:       "/projects/{projectId}/jobs/{jobId}/cancel",
		HTTPMethod: "POST",
		Handler:    &jobsCancelHandler{},
	},
	{
		Path:       "/projects/{projectsId}/jobs/{jobsId}/delete",
		HTTPMethod: "DELETE",
		Handler:    &jobsDeleteHandler{},
	},
	{
		Path:       "/projects/{projectId}/jobs/{jobId}",
		HTTPMethod: "GET",
		Handler:    &jobsGetHandler{},
	},
	{
		Path:       "/projects/{projectId}/queries/{jobId}",
		HTTPMethod: "GET",
		Handler:    &jobsGetQueryResultsHandler{},
	},
	{
		Path:       "/projects/{projectId}/jobs",
		HTTPMethod: "POST",
		Handler:    &jobsInsertHandler{},
	},
	{
		Path:       "/projects/{projectId}/jobs",
		HTTPMethod: "GET",
		Handler:    &jobsListHandler{},
	},
	{
		Path:       "/projects/{projectId}/queries",
		HTTPMethod: "POST",
		Handler:    &jobsQueryHandler{},
	},
	{
		Path:       "/projects/{projectsId}/datasets/{datasetsId}/models/{modelsId}",
		HTTPMethod: "DELETE",
		Handler:    &modelsDeleteHandler{},
	},
	{
		Path:       "/projects/{projectsId}/datasets/{datasetsId}/models/{modelsId}",
		HTTPMethod: "GET",
		Handler:    &modelsGetHandler{},
	},
	{
		Path:       "/projects/{projectsId}/datasets/{datasetsId}/models",
		HTTPMethod: "GET",
		Handler:    &modelsListHandler{},
	},
	{
		Path:       "/projects/{projectsId}/datasets/{datasetsId}/models/{modelsId}",
		HTTPMethod: "PATCH",
		Handler:    &modelsPatchHandler{},
	},
	{
		Path:       "/projects/{projectId}/serviceAccount",
		HTTPMethod: "GET",
		Handler:    &projectsGetServiceAccountHandler{},
	},
	{
		Path:       "/projects",
		HTTPMethod: "GET",
		Handler:    &projectsListHandler{},
	},
	{
		Path:       "/projects/{projectsId}/datasets/{datasetsId}/routines/{routinesId}",
		HTTPMethod: "DELETE",
		Handler:    &routinesDeleteHandler{},
	},
	{
		Path:       "/projects/{projectsId}/datasets/{datasetsId}/routines/{routinesId}",
		HTTPMethod: "GET",
		Handler:    &routinesGetHandler{},
	},
	{
		Path:       "/projects/{projectsId}/datasets/{datasetsId}/routines",
		HTTPMethod: "POST",
		Handler:    &routinesInsertHandler{},
	},
	{
		Path:       "/projects/{projectsId}/datasets/{datasetsId}/routines",
		HTTPMethod: "GET",
		Handler:    &routinesListHandler{},
	},
	{
		Path:       "/projects/{projectsId}/datasets/{datasetsId}/routines/{routinesId}",
		HTTPMethod: "PUT",
		Handler:    &routinesUpdateHandler{},
	},
	{
		Path:       "/projects/{projectsId}/datasets/{datasetsId}/tables/{tablesId}/rowAccessPolicies/{rowAccessPoliciesId}:getIamPolicy",
		HTTPMethod: "POST",
		Handler:    &rowAccessPoliciesGetIamPolicyHandler{},
	},
	{
		Path:       "/projects/{projectsId}/datasets/{datasetsId}/tables/{tablesId}/rowAccessPolicies",
		HTTPMethod: "GET",
		Handler:    &rowAccessPoliciesListHandler{},
	},
	{
		Path:       "/projects/{projectsId}/datasets/{datasetsId}/tables/{tablesId}/rowAccessPolicies/{rowAccessPoliciesId}:setIamPolicy",
		HTTPMethod: "POST",
		Handler:    &rowAccessPoliciesSetIamPolicyHandler{},
	},
	{
		Path:       "/projects/{projectsId}/datasets/{datasetsId}/tables/{tablesId}/rowAccessPolicies/{rowAccessPoliciesId}:testIamPermissions",
		HTTPMethod: "POST",
		Handler:    &rowAccessPoliciesTestIamPermissionsHandler{},
	},
	{
		Path:       "/projects/{projectId}/datasets/{datasetId}/tables/{tableId}/insertAll",
		HTTPMethod: "POST",
		Handler:    &tabledataInsertAllHandler{},
	},
	{
		Path:       "/projects/{projectId}/datasets/{datasetId}/tables/{tableId}/data",
		HTTPMethod: "GET",
		Handler:    &tabledataListHandler{},
	},
	{
		Path:       "/projects/{projectId}/datasets/{datasetId}/tables/{tableId}",
		HTTPMethod: "DELETE",
		Handler:    &tablesDeleteHandler{},
	},
	{
		Path:       "/projects/{projectId}/datasets/{datasetId}/tables/{tableId}",
		HTTPMethod: "GET",
		Handler:    &tablesGetHandler{},
	},
	{
		Path:       "/projects/{projectsId}/datasets/{datasetsId}/tables/{tablesId}:getIamPolicy",
		HTTPMethod: "POST",
		Handler:    &tablesGetIamPolicyHandler{},
	},
	{
		Path:       "/projects/{projectId}/datasets/{datasetId}/tables",
		HTTPMethod: "POST",
		Handler:    &tablesInsertHandler{},
	},
	{
		Path:       "/projects/{projectId}/datasets/{datasetId}/tables",
		HTTPMethod: "GET",
		Handler:    &tablesListHandler{},
	},
	{
		Path:       "/projects/{projectId}/datasets/{datasetId}/tables/{tableId}",
		HTTPMethod: "PATCH",
		Handler:    &tablesPatchHandler{},
	},
	{
		Path:       "/projects/{projectsId}/datasets/{datasetsId}/tables/{tablesId}:setIamPolicy",
		HTTPMethod: "POST",
		Handler:    &tablesSetIamPolicyHandler{},
	},
	{
		Path:       "/projects/{projectsId}/datasets/{datasetsId}/tables/{tablesId}:testIamPermissions",
		HTTPMethod: "POST",
		Handler:    &tablesTestIamPermissionsHandler{},
	},
	{
		Path:       "/projects/{projectId}/datasets/{datasetId}/tables/{tableId}",
		HTTPMethod: "PUT",
		Handler:    &tablesUpdateHandler{},
	},
}

var (
	_ http.Handler = &datasetsDeleteHandler{}
	_ http.Handler = &datasetsGetHandler{}
	_ http.Handler = &datasetsInsertHandler{}
	_ http.Handler = &datasetsListHandler{}
	_ http.Handler = &datasetsPatchHandler{}
	_ http.Handler = &datasetsUpdateHandler{}
	_ http.Handler = &jobsCancelHandler{}
	_ http.Handler = &jobsDeleteHandler{}
	_ http.Handler = &jobsGetHandler{}
	_ http.Handler = &jobsGetQueryResultsHandler{}
	_ http.Handler = &jobsInsertHandler{}
	_ http.Handler = &jobsListHandler{}
	_ http.Handler = &jobsQueryHandler{}
	_ http.Handler = &modelsDeleteHandler{}
	_ http.Handler = &modelsGetHandler{}
	_ http.Handler = &modelsListHandler{}
	_ http.Handler = &modelsPatchHandler{}
	_ http.Handler = &projectsGetServiceAccountHandler{}
	_ http.Handler = &projectsListHandler{}
	_ http.Handler = &routinesDeleteHandler{}
	_ http.Handler = &routinesGetHandler{}
	_ http.Handler = &routinesInsertHandler{}
	_ http.Handler = &routinesListHandler{}
	_ http.Handler = &routinesUpdateHandler{}
	_ http.Handler = &rowAccessPoliciesGetIamPolicyHandler{}
	_ http.Handler = &rowAccessPoliciesListHandler{}
	_ http.Handler = &rowAccessPoliciesSetIamPolicyHandler{}
	_ http.Handler = &rowAccessPoliciesTestIamPermissionsHandler{}
	_ http.Handler = &tabledataInsertAllHandler{}
	_ http.Handler = &tabledataListHandler{}
	_ http.Handler = &tablesDeleteHandler{}
	_ http.Handler = &tablesGetHandler{}
	_ http.Handler = &tablesGetIamPolicyHandler{}
	_ http.Handler = &tablesInsertHandler{}
	_ http.Handler = &tablesListHandler{}
	_ http.Handler = &tablesPatchHandler{}
	_ http.Handler = &tablesSetIamPolicyHandler{}
	_ http.Handler = &tablesTestIamPermissionsHandler{}
	_ http.Handler = &tablesUpdateHandler{}
)

type datasetsDeleteHandler struct {
}

type datasetsGetHandler struct {
}

type datasetsInsertHandler struct {
}

type datasetsListHandler struct {
}

type datasetsPatchHandler struct {
}

type datasetsUpdateHandler struct {
}

type jobsCancelHandler struct {
}

type jobsDeleteHandler struct {
}

type jobsGetHandler struct {
}

type jobsGetQueryResultsHandler struct {
}

type jobsInsertHandler struct {
}

type jobsListHandler struct {
}

type jobsQueryHandler struct {
}

type modelsDeleteHandler struct {
}

type modelsGetHandler struct {
}

type modelsListHandler struct {
}

type modelsPatchHandler struct {
}

type projectsGetServiceAccountHandler struct {
}

type projectsListHandler struct {
}

type routinesDeleteHandler struct {
}

type routinesGetHandler struct {
}

type routinesInsertHandler struct {
}

type routinesListHandler struct {
}

type routinesUpdateHandler struct {
}

type rowAccessPoliciesGetIamPolicyHandler struct {
}

type rowAccessPoliciesListHandler struct {
}

type rowAccessPoliciesSetIamPolicyHandler struct {
}

type rowAccessPoliciesTestIamPermissionsHandler struct {
}

type tabledataInsertAllHandler struct {
}

type tabledataListHandler struct {
}

type tablesDeleteHandler struct {
}

type tablesGetHandler struct {
}

type tablesGetIamPolicyHandler struct {
}

type tablesInsertHandler struct {
}

type tablesListHandler struct {
}

type tablesPatchHandler struct {
}

type tablesSetIamPolicyHandler struct {
}

type tablesTestIamPermissionsHandler struct {
}

type tablesUpdateHandler struct {
}
