name: build and test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - name: download modules
        run: go mod download
      - name: build
        run: make emulator/build
        env:
          VERSION: test
      - name: show version
        run: ./bigquery-emulator --version
  test:
    name: Test
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - name: download modules
        run: go mod download
      - name: test
        run: go test ./... -count=1 -timeout 600s
